#
# These are the same as the defaults.
#
quarkus.index-dependency.cs548.group-id=edu.stevens.cs548
quarkus.package.jar.type=fast-jar
quarkus.http.port=8080
%dev.quarkus.http.port=5050
#
# End point and properties for health check
#
quarkus.smallrye-health.root-path=/health
memory.threshold=10485760
database.port=5432
database.host=clinic-database
%dev.database.host=localhost
#
# Container image build
#
quarkus.container-image.build=true
quarkus.container-image.group=cs548
quarkus.container-image.name=clinic-domain
#
# Customization of serialization
#
# Enabling this causes problems with serializing lists of treatments.
#
# quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true