#
# Data source
#
quarkus.datasource.db-kind = postgresql
quarkus.datasource.jdbc.max-size = 14

%dev.quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/clinic
%dev.quarkus.datasource.username=clinicuser
%dev.quarkus.datasource.password=clinicpass

%prod.quarkus.datasource.jdbc.url = jdbc:postgresql://clinic-database:5432/clinic

#
# Persistence unit that uses this datasource
#
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.packages=edu.stevens.cs548.clinic.domain
quarkus.hibernate-orm.schema-management.create-schemas=true