#
# These are the same as the defaults.
#
quarkus.index-dependency.acme.group-id=edu.stevens.cs548
quarkus.package.jar.type=fast-jar
quarkus.http.port=8080
%dev.quarkus.http.port=9090

#
# Container image build
#
quarkus.container-image.build=true
quarkus.container-image.group=cs548
quarkus.container-image.name=clinic-rest
#
# Enabling this causes problems with serializing lists of treatments.
#
# quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true