#
# Endpoint URL for the microservice
#
quarkus.rest-client.clinic-domain-api.url=http://clinic-domain:8080/api
%dev.quarkus.rest-client.clinic-domain-api.url=http://localhost:5050/api

# quarkus.rest-client.clinic-domain-api.scope=jakarta.inject.Singleton

#
# Do NOT use in a production system
# Trust all TLS certificates and disable hostname verification.
#
quarkus.tls.tls-disabled.trust-all=true
quarkus.tls.tls-disabled.hostname-verification-algorithm=NONE
quarkus.rest-client.clinic-domain-api.tls-configuration-name=tls-disabled
#
# Default mapper throws an exception if the response is >= 400.
#
# quarkus.rest-client.clinic-domain-api.disable-default-mapper=true

