apiVersion: v1
kind: Service
metadata:
  name: clinic-database
  labels:
    app: clinic-database
spec:
  type: NodePort
  ports:
    - name: jdbc
      port: 5432
      targetPort: 5432
  selector:
    app: clinic-database
